services:
  fastapi:
    build: .
    container_name: fastapi_calculator
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app

  # PostgreSQL service
  # postgres:
  #   image: postgres:13
  #   container_name: postgres
  #   ports:
  #     - "5432:5432"  # Expose PostgreSQL on port 5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=calculator_db  # Create a calculator_db database
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL data
  #   restart: always

  # # pgAdmin service
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   ports:
  #     - "8080:80"  # Expose pgAdmin on port 8080
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com  # Default admin email for pgAdmin
  #     - PGADMIN_DEFAULT_PASSWORD=admin  # Default admin password for pgAdmin
  #   depends_on:
  #     - postgres
  #   restart: always

# volumes:
#   postgres_data:
#     driver: local
